
name: yaml to json

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML

      - name: Convert all yaml to json 
        run: find . -type f -name \*.yml -not -path "*/.*" -exec sh -c 'cat "$1" | python -c "import sys, yaml, json; json.dump(yaml.safe_load(sys.stdin), sys.stdout, indent=4)" > ${1%.yml}.json'  sh {} \;

      - name: Commit JSON
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -am "Commit JSON files"
          git push origin main:json --force
